<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Setting -  Maintenance
    |--------------------------------------------------------------------------
    */
    [
        'permission' => 'state',
        'title' => 'State',
        'group' => 'maintenance',
        'index' =>  '1',
        'route' => 'setting.maintenance.state',
    ],
    [
        'permission' => 'relationship',
        'title' => 'Relationship',
        'group' => 'maintenance',
        'index' =>  '1',
        'route' => 'setting.maintenance.relationship',
    ],
    [
        'permission' => 'religion',
        'title' => 'Religion',
        'group' => 'maintenance',
        'index' =>  '1',
        'route' => 'setting.maintenance.religion',
    ],
    [
        'permission' => 'race',
        'title' => 'Race',
        'group' => 'maintenance',
        'index' =>  '1',
        'route' => 'setting.maintenance.race',
    ],
    [
        'permission' => 'gl code',
        'title' => 'GL Code',
        'group' => 'maintenance',
        'index' =>  '1',
        'route' => 'setting.maintenance.glcode',
    ],
    [
        'permission' => 'gender',
        'title' => 'Gender',
        'group' => 'maintenance',
        'index' =>  '1',
        'route' => 'setting.maintenance.gender',
    ],
    [
        'permission' => 'title',
        'title' => 'Title',
        'group' => 'maintenance',
        'index' =>  '1',
        'route' => 'setting.maintenance.title',
    ],
    [
        'permission' => 'marital',
        'title' => 'Marital',
        'group' => 'maintenance',
        'index' =>  '1',
        'route' => 'setting.maintenance.title',
    ],
    [
        'permission' => 'education',
        'title' => 'Education',
        'group' => 'maintenance',
        'index' =>  '1',
        'route' => 'setting.maintenance.education',
    ],
    [
        'permission' => 'bank',
        'title' => 'Bank',
        'group' => 'maintenance',
        'index' =>  '1',
        'route' => 'setting.maintenance.banks',
    ],
    [
        'permission' => 'country',
        'title' => 'Country',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.country',
    ],
    [
        'permission' => 'financing rule',
        'title' => 'Financing Rule',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.financing-rule',
    ],
    [
        'permission' => 'address type',
        'title' => 'Address Type',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.address-type',
    ],
    [
        'permission' => 'languages',
        'title' => 'Languages',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.languages',
    ],
    [
        'permission' => 'identity type',
        'title' => 'Identity Type',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.identity-type',
    ],
    [
        'permission' => 'third party',
        'title' => 'Third Party',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.third-party',
    ],
    [
        'permission' => 'member status',
        'title' => 'Member Status',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.member-status',
    ],
    [
        'permission' => 'branch id',
        'title' => 'Branch Id',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.branch-id',
    ],
    [
        'permission' => 'position',
        'title' => 'Position',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.position',
    ],
    [
        'permission' => 'income',
        'title' => 'Income',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.income',
    ],
    [
        'permission' => 'job status',
        'title' => 'Job Status',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.job-status',
    ],
    [
        'permission' => 'occupation',
        'title' => 'Occupation',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.occupation',
    ],
    [
        'permission' => 'concept code',
        'title' => 'Concept Code',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.concept-code',
    ],
    [
        'permission' => 'department',
        'title' => 'Department',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.department',
    ],
    [
        'permission' => 'customer type',
        'title' => 'Customer Type',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.cust-type',
    ],
    [
        'permission' => 'takaful',
        'title' => 'Takaful',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.takaful',
    ],
    [
        'permission' => 'guarantor status',
        'title' => 'Guarantor Status',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.guarantor-status',
    ],
    [
        'permission' => 'inst code',
        'title' => 'Inst Code',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.inst-codes',
    ],
    [
        'permission' => 'inst mode',
        'title' => 'Inst Mode',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.inst-modes',
    ],
    [
        'permission' => 'code status',
        'title' => 'Code Status',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.cust-status',
    ],
    [
        'permission' => 'employer list',
        'title' => 'Employer List',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.employer-list',
    ],
    [
        'permission' => 'payment type',
        'title' => 'Payment Type',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.payment-type',
    ],
    [
        'permission' => 'product',
        'title' => 'Product',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.products',
    ],
    [
        'permission' => 'virtual account',
        'title' => 'Virtual Account',
        'group' => 'maintenance',
        'index' => '1',
        'route' => 'setting.maintenance.virtual-acc',
    ],
    
];
