name: Pull from Windows Server

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  pull_from_windows_server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > C:\Users\Administrator\.ssh\id_rsa && chmod 600 C:\Users\Administrator\.ssh\id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> C:\Users\Administrator\.ssh\known_hosts

    - name: Pull from Windows server
      run: |
        ssh -i C:\Users\Administrator\.ssh\id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"
